name: GoalVerse Auto Upload

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */8 * * *"

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create OAuth Files
        run: |
          echo '${{ secrets.YOUTUBE_TOKEN_JSON }}' > token.json
          echo '${{ secrets.YOUTUBE_OAUTH_JSON }}' > oauth.json

      - name: Run GoalVerse
        run: python main.py
